// Auto-generated from source_map_regions.csv
// Each source is tagged by Region and has an 'Use' hint that helps classify signal type.
module.exports = [
  {region:"Global/Europe", name:"TED", url:"https://ted.europa.eu/en/", type:"procurement", rss:null},
  {region:"UK", name:"Find a Tender", url:"https://www.find-tender.service.gov.uk/Search/Results", type:"procurement", rss:null},
  {region:"UK", name:"Contracts Finder", url:"https://www.gov.uk/contracts-finder", type:"procurement", rss:null},
  {region:"Europe", name:"The Bookseller", url:"https://www.thebookseller.com", type:"news", rss:"https://www.thebookseller.com/feed"},
  {region:"Europe", name:"Jobs in Books", url:"https://jobs.thebookseller.com", type:"hiring", rss:null},
  {region:"Europe", name:"EdSurge", url:"https://www.edsurge.com/news", type:"news", rss:"https://www.edsurge.com/news.rss"},
  {region:"Europe", name:"1EdTech", url:"https://www.1edtech.org", type:"standards", rss:null},
  {region:"Europe", name:"EU Digital Skills and Jobs Platform", url:"https://digital-skills-jobs.europa.eu/en/initiatives/funding/edtech-accelerator", type:"funding", rss:null},
  {region:"Europe", name:"Brighteye", url:"https://www.brighteyevc.com/", type:"funding", rss:null},
  {region:"Europe", name:"EIPA", url:"https://www.eipa.eu", type:"public-sector", rss:null},
  {region:"Europe", name:"DevelopmentAid", url:"https://www.developmentaid.org", type:"hiring", rss:null},
  {region:"Europe", name:"Tendermetric education tenders", url:"https://tendermetric.com/sector/education", type:"procurement", rss:null},
  {region:"Europe", name:"European Procurement Forum", url:"https://eupf.org", type:"procurement", rss:null},
  {region:"Europe", name:"Excelsoft website", url:"https://www.excelsoftcorp.com", type:"company", rss:null},
  {region:"USA", name:"EdSurge", url:"https://www.edsurge.com/news", type:"news", rss:"https://www.edsurge.com/news.rss"},
  {region:"USA", name:"SETDA", url:"https://www.setda.org/priorities/digital-content/procurement/", type:"procurement", rss:null},
  {region:"USA", name:"Digital Promise", url:"https://digitalpromise.org", type:"research", rss:null},
  {region:"USA", name:"OECD digital education outlook", url:"https://www.oecd.org/en/publications/oecd-digital-education-outlook-2023_c74f03de-en/full-report/", type:"policy", rss:null},
  {region:"Middle East", name:"J360 Middle-East tenders", url:"https://www.j360.info/en/tenders/middle-east/?act=education-trainings", type:"procurement", rss:null},
  {region:"Middle East", name:"DataHorizzon research", url:"https://datahorizzonresearch.com/middle-east-edtech-market-59855", type:"research", rss:null},
  {region:"APAC", name:"EduTECH AU", url:"https://www.edutech.net.au/", type:"event", rss:null},
  {region:"APAC", name:"NSW Education procurement", url:"https://education.nsw.gov.au/partnering-with-us/supplying-to-us/supplying-it-goods-and-services", type:"procurement", rss:null},
  {region:"APAC", name:"VicGov procurement", url:"https://www.vic.gov.au/procurement-department-education", type:"procurement", rss:null},
  {region:"India", name:"EdTech Tulna", url:"https://wsai.iitm.ac.in/projects/edtech-tulna/", type:"framework", rss:null},
  {region:"India", name:"UNESCO India case study", url:"https://unesdoc.unesco.org/ark:/48223/pf0000386079.locale=en", type:"research", rss:null},
  {region:"Africa", name:"UNICEF Africa school connectivity", url:"https://www.edtechinnovationhub.com/news/unicef-to-connect-500000-african-schools-to-the-internet-through-large-scale-procurement", type:"procurement", rss:null},
  {region:"Africa", name:"Betar Africa", url:"https://www.betar.africa/2026/04/03/africas-edtech-b2g-pivot-when-governments-become-the-customer/", type:"trend", rss:null},
  {region:"Australia", name:"EDUtech AU", url:"https://www.edutech.net.au/", type:"event", rss:null},
  {region:"South America", name:"EdSurge global coverage", url:"https://www.edsurge.com/news", type:"news", rss:"https://www.edsurge.com/news.rss"},
  {region:"Canada", name:"EdSurge", url:"https://www.edsurge.com/news", type:"news", rss:"https://www.edsurge.com/news.rss"}
];